---

- name: apt | apache-security packages install
  apt: name={{item}} state=present
  with_items:
    - python-passlib
    - apache2
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- set_fact:
    hardenwebserver_apachesecurityconf: /etc/apache2/conf-available/security.conf
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: yum | apache-security packages install
  yum: name={{item}} state=present
  with_items:
    - python-passlib
    - httpd
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- set_fact:
    hardenwebserver_apachesecurityconf: /etc/httpd/conf.d/security.conf
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

## headers for security.conf, reqtimeout for modsecurity slow attacks
# https://www.acunetix.com/blog/articles/slow-http-dos-attacks-mitigate-apache-http-server/
- name: Enabled extra modules
  apache2_module: state=present name="{{ item }}"
  with_items:
    - headers
    - reqtimeout
  notify:
    - restart apache
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

## Note: commented headers can break some apps like nagios
- name: Enabled extra security headers
  replace: dest="{{ hardenwebserver_apachesecurityconf }}" regexp="{{ item.re }}" replace="{{ item.n }}"
  with_items:
    - { re: '^#ServerTokens Minimal', n: 'ServerTokens Minimal' }
    - { re: '^ServerTokens OS', n: '#ServerTokens OS' }
    - { re: '^#ServerSignature Off', n: 'ServerSignature Off' }
    - { re: '^ServerSignature On', n: '#ServerSignature On' }
    - { re: '^#Header set X-Content-Type-Options: "nosniff"', n: 'Header set X-Content-Type-Options: "nosniff"' }
    - { re: '^#Header set X-Frame-Options: "sameorigin"', n: 'Header set X-Frame-Options: "sameorigin"' }
#    - { re: '^#Header set X-Frame-Options: "sameorigin"', n: 'Header set X-Frame-Options: "deny"' }
  notify:
    - restart apache
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

## https://www.owasp.org/index.php/List_of_useful_HTTP_headers
- name: Enabled extra security headers
  lineinfile: dest="{{ hardenwebserver_apachesecurityconf }}" line="{{ item.n }}"
  with_items:
    - { n: 'Header set Strict-Transport-Security "max-age=16070400; includeSubDomains"' }
#    - { n: 'Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains; preload"' }
    - { n: 'Header set X-XSS-Protection "1; mode=block"' }
#    - { n: 'Header set Content-Security-Policy "default-src self"' }
  notify:
    - restart apache
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Enabled extra security headers
  lineinfile: >
    dest="{{ hardenwebserver_apachesecurityconf }}"
    line="{{ item }}"
    create=yes
  with_items:
    - 'ServerTokens Minimal'
    - 'ServerSignature Off'
    - 'Header set X-Content-Type-Options: "nosniff"'
    - 'Header set X-Frame-Options: "sameorigin"'
#    - 'Header set X-Frame-Options: "deny"'
## FIXME! problem w escaping ;
#    - 'Header set Strict-Transport-Security "max-age=16070400; includeSubDomains"'
#    - 'Header set X-XSS-Protection "1; mode=block"'
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

