---

- name: yum | apache-ssl packages install
  yum: name={{item}} state=present
  with_items:
    - mod_ssl
    - openssl
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- set_fact:
- include: certificate-selfsigned.yml

- name: update certificate info
  replace: dest=/etc/apache2/sites-available/default-ssl.conf regexp='{{ item.regexp }}' replace='{{ item.replace }}'
  with_items:
    - { regexp: '/etc/ssl/certs/ssl-cert-snakeoil.pem', replace: '/etc/ssl/{{ ansible_fqdn }}.crt' }
    - { regexp: '/etc/ssl/private/ssl-cert-snakeoil.key', replace: '/etc/ssl/private/{{ ansible_fqdn }}.key' }
  notify:
    - restart apache
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- apache2_module: name=ssl state=present
  notify:
    - restart apache
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: enable ssl apache site
  file: src=/etc/apache2/sites-available/default-ssl.conf dest=/etc/apache2/sites-enabled/default-ssl.conf state=link
  notify:
    - restart apache
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

## https://cipherli.st/
- name: Enabled extra SSL security headers
  lineinfile: dest="{{ apachesslconf }}" line="{{ item.n }}" insertafter="SSLEngine on"
  with_items:
    - { n: '        SSLCipherSuite EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH' }
    - { n: '        SSLProtocol All -SSLv2 -SSLv3' }
    - { n: '        SSLHonorCipherOrder On' }
## Requires Apache >= 2.4
    - { n: '        SSLCompression off' }
    - { n: '        SSLUseStapling on' }
## Requires Apache >= 2.4.12
#    - { n: '       SSLSessionTickets Off' }
  notify:
    - restart apache
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Enabled extra SSL security headers (2)
  lineinfile: dest="{{ apachesslconf }}" line="{{ item.n }}" insertafter="</VirtualHost>"
  with_items:
## Requires Apache >= 2.4
    - { n: '    SSLStaplingCache "shmcb:logs/stapling-cache(150000)"' }
  notify:
    - restart apache
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

