---

- set_fact:
    www_user: www-data
    apache_svc: nginx
    apache_confdir: /etc/nginx/conf.d
    apache_sitedir: /etc/nginx/sites-available
    apacheconf: /etc/nginx/nginx.conf
    apachedefault: /etc/nginx/sites-available/default
    modsecurity_conf: /etc/modsecurity/modsecurity.conf
    modsecurity_active: /usr/share/modsecurity-crs/activated_rules
    hardenwebserver_apachesecurityconf: /etc/apache2/conf-available/security.conf
    hardenwebserver_nginx_naxsi: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- set_fact:
    www_user: nginx
    apache_svc: nginx
    apache_confdir: /etc/nginx/default.d
    apache_sitedir: /etc/nginx/conf.d
    apachesslconf: /etc/apache2/sites-enabled/default-ssl.conf
    modsecurity_conf: /etc/httpd/conf.d/mod_security.conf
    modsecurity_active: /etc/httpd/modsecurity.d/activated_rules
    hardenwebserver_apachesecurityconf: /etc/httpd/conf.d/security.conf
    hardenwebserver_nginx_naxsi: false
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

