---

- name: apt | nginx packages install
  apt: name={{item}} state=present
  with_items:
    - python-passlib
#    - nginx
    - nginx-naxsi
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: yum | nginx packages install
  yum: name={{item}} state=present
  with_items:
    - python-passlib
    - nginx
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include: nginx-env.yml
- include: nginx-security.yml

- name: ensure nginx is enabled and started
  service: name={{ apache_svc }} state=started enabled=yes
